var annotated_dup =
[
    [ "Photon", "namespace_photon.html", [
      [ "Chat", "namespace_photon_1_1_chat.html", [
        [ "Demo", "namespace_photon_1_1_chat_1_1_demo.html", [
          [ "AppSettingsExtensions", "class_photon_1_1_chat_1_1_demo_1_1_app_settings_extensions.html", "class_photon_1_1_chat_1_1_demo_1_1_app_settings_extensions" ],
          [ "ChannelSelector", "class_photon_1_1_chat_1_1_demo_1_1_channel_selector.html", "class_photon_1_1_chat_1_1_demo_1_1_channel_selector" ],
          [ "ChatAppIdCheckerUI", "class_photon_1_1_chat_1_1_demo_1_1_chat_app_id_checker_u_i.html", "class_photon_1_1_chat_1_1_demo_1_1_chat_app_id_checker_u_i" ],
          [ "ChatGui", "class_photon_1_1_chat_1_1_demo_1_1_chat_gui.html", "class_photon_1_1_chat_1_1_demo_1_1_chat_gui" ],
          [ "FriendItem", "class_photon_1_1_chat_1_1_demo_1_1_friend_item.html", "class_photon_1_1_chat_1_1_demo_1_1_friend_item" ],
          [ "IgnoreUiRaycastWhenInactive", "class_photon_1_1_chat_1_1_demo_1_1_ignore_ui_raycast_when_inactive.html", "class_photon_1_1_chat_1_1_demo_1_1_ignore_ui_raycast_when_inactive" ],
          [ "NamePickGui", "class_photon_1_1_chat_1_1_demo_1_1_name_pick_gui.html", "class_photon_1_1_chat_1_1_demo_1_1_name_pick_gui" ]
        ] ],
        [ "UtilityScripts", "namespace_photon_1_1_chat_1_1_utility_scripts.html", [
          [ "EventSystemSpawner", "class_photon_1_1_chat_1_1_utility_scripts_1_1_event_system_spawner.html", "class_photon_1_1_chat_1_1_utility_scripts_1_1_event_system_spawner" ],
          [ "OnStartDelete", "class_photon_1_1_chat_1_1_utility_scripts_1_1_on_start_delete.html", "class_photon_1_1_chat_1_1_utility_scripts_1_1_on_start_delete" ],
          [ "TextButtonTransition", "class_photon_1_1_chat_1_1_utility_scripts_1_1_text_button_transition.html", "class_photon_1_1_chat_1_1_utility_scripts_1_1_text_button_transition" ],
          [ "TextToggleIsOnTransition", "class_photon_1_1_chat_1_1_utility_scripts_1_1_text_toggle_is_on_transition.html", "class_photon_1_1_chat_1_1_utility_scripts_1_1_text_toggle_is_on_transition" ]
        ] ],
        [ "ChannelCreationOptions", "class_photon_1_1_chat_1_1_channel_creation_options.html", "class_photon_1_1_chat_1_1_channel_creation_options" ],
        [ "ChannelWellKnownProperties", "class_photon_1_1_chat_1_1_channel_well_known_properties.html", "class_photon_1_1_chat_1_1_channel_well_known_properties" ],
        [ "ChatAppSettings", "class_photon_1_1_chat_1_1_chat_app_settings.html", "class_photon_1_1_chat_1_1_chat_app_settings" ],
        [ "ChatChannel", "class_photon_1_1_chat_1_1_chat_channel.html", "class_photon_1_1_chat_1_1_chat_channel" ],
        [ "ChatClient", "class_photon_1_1_chat_1_1_chat_client.html", "class_photon_1_1_chat_1_1_chat_client" ],
        [ "ChatEventCode", "class_photon_1_1_chat_1_1_chat_event_code.html", "class_photon_1_1_chat_1_1_chat_event_code" ],
        [ "ChatOperationCode", "class_photon_1_1_chat_1_1_chat_operation_code.html", "class_photon_1_1_chat_1_1_chat_operation_code" ],
        [ "ChatParameterCode", "class_photon_1_1_chat_1_1_chat_parameter_code.html", "class_photon_1_1_chat_1_1_chat_parameter_code" ],
        [ "ChatPeer", "class_photon_1_1_chat_1_1_chat_peer.html", "class_photon_1_1_chat_1_1_chat_peer" ],
        [ "AuthenticationValues", "class_photon_1_1_chat_1_1_authentication_values.html", "class_photon_1_1_chat_1_1_authentication_values" ],
        [ "ParameterCode", "class_photon_1_1_chat_1_1_parameter_code.html", "class_photon_1_1_chat_1_1_parameter_code" ],
        [ "ErrorCode", "class_photon_1_1_chat_1_1_error_code.html", "class_photon_1_1_chat_1_1_error_code" ],
        [ "ChatUserStatus", "class_photon_1_1_chat_1_1_chat_user_status.html", "class_photon_1_1_chat_1_1_chat_user_status" ],
        [ "IChatClientListener", "interface_photon_1_1_chat_1_1_i_chat_client_listener.html", "interface_photon_1_1_chat_1_1_i_chat_client_listener" ]
      ] ],
      [ "Pun", "namespace_photon_1_1_pun.html", [
        [ "Demo", "namespace_photon_1_1_pun_1_1_demo.html", [
          [ "Asteroids", "namespace_photon_1_1_pun_1_1_demo_1_1_asteroids.html", [
            [ "AsteroidsGame", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroids_game.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroids_game" ],
            [ "Asteroid", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroid.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroid" ],
            [ "AsteroidsGameManager", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroids_game_manager.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_asteroids_game_manager" ],
            [ "Bullet", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_bullet.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_bullet" ],
            [ "PlayerOverviewPanel", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_player_overview_panel.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_player_overview_panel" ],
            [ "Spaceship", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_spaceship.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_spaceship" ],
            [ "LobbyMainPanel", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_lobby_main_panel.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_lobby_main_panel" ],
            [ "LobbyTopPanel", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_lobby_top_panel.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_lobby_top_panel" ],
            [ "PlayerListEntry", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_player_list_entry.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_player_list_entry" ],
            [ "RoomListEntry", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_room_list_entry.html", "class_photon_1_1_pun_1_1_demo_1_1_asteroids_1_1_room_list_entry" ]
          ] ],
          [ "Cockpit", "namespace_photon_1_1_pun_1_1_demo_1_1_cockpit.html", [
            [ "Forms", "namespace_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms.html", [
              [ "ConnectToRegionUIForm", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_connect_to_region_u_i_form.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_connect_to_region_u_i_form" ],
              [ "CreateRoomUiForm", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_create_room_ui_form.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_create_room_ui_form" ],
              [ "LoadLevelUIForm", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_load_level_u_i_form.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_load_level_u_i_form" ],
              [ "SetRoomCustomPropertyUIForm", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_set_room_custom_property_u_i_form.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_set_room_custom_property_u_i_form" ],
              [ "UserIdUiForm", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_user_id_ui_form.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_forms_1_1_user_id_ui_form" ]
            ] ],
            [ "PunCockpit", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_pun_cockpit.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_pun_cockpit" ],
            [ "AutoSyncSceneToggle", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_auto_sync_scene_toggle.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_auto_sync_scene_toggle" ],
            [ "BackgroundTimeOutField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_background_time_out_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_background_time_out_field" ],
            [ "CrcCheckToggle", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_crc_check_toggle.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_crc_check_toggle" ],
            [ "CurrentRoomIsOpenToggle", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_open_toggle.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_open_toggle" ],
            [ "CurrentRoomIsVisibleToggle", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_visible_toggle.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_visible_toggle" ],
            [ "DocLinkButton", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_doc_link_button.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_doc_link_button" ],
            [ "GameVersionField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_game_version_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_game_version_field" ],
            [ "BoolInputField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_bool_input_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_bool_input_field" ],
            [ "IntInputField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_int_input_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_int_input_field" ],
            [ "StringInputField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_string_input_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_string_input_field" ],
            [ "ToggleExpand", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_toggle_expand.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_toggle_expand" ],
            [ "LayoutElementMatchSize", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_layout_element_match_size.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_layout_element_match_size" ],
            [ "NickNameField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_nick_name_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_nick_name_field" ],
            [ "OnlineDocButton", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_online_doc_button.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_online_doc_button" ],
            [ "SendRateField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_send_rate_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_send_rate_field" ],
            [ "SendRateOnSerializeField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_send_rate_on_serialize_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_send_rate_on_serialize_field" ],
            [ "PlayerDetailsController", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_details_controller.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_details_controller" ],
            [ "InfosPanelPlaceholder", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_infos_panel_placeholder.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_infos_panel_placeholder" ],
            [ "FriendListCell", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_friend_list_cell.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_friend_list_cell" ],
            [ "FriendListView", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_friend_list_view.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_friend_list_view" ],
            [ "PlayerListCell", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_list_cell.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_list_cell" ],
            [ "PlayerListView", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_list_view.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_player_list_view" ],
            [ "PropertyCell", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_property_cell.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_property_cell" ],
            [ "RegionListCell", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_region_list_cell.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_region_list_cell" ],
            [ "RegionListView", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_region_list_view.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_region_list_view" ],
            [ "RoomListCell", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_room_list_cell.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_room_list_cell" ],
            [ "RoomListView", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_room_list_view.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_room_list_view" ],
            [ "UserIdField", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_user_id_field.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_user_id_field" ],
            [ "AppVersionProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_app_version_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_app_version_property" ],
            [ "BestRegionInPrefsProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_best_region_in_prefs_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_best_region_in_prefs_property" ],
            [ "CloudRegionProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_cloud_region_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_cloud_region_property" ],
            [ "CountOfPlayersInRoomProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_in_room_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_in_room_property" ],
            [ "CountOfPlayersOnMasterProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_on_master_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_on_master_property" ],
            [ "CountOfPlayersProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_players_property" ],
            [ "CountOfRoomsProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_rooms_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_count_of_rooms_property" ],
            [ "CurrentRoomAutoCleanupProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_auto_cleanup_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_auto_cleanup_property" ],
            [ "CurrentRoomEmptyRoomTtlProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_empty_room_ttl_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_empty_room_ttl_property" ],
            [ "CurrentRoomExpectedUsersProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_expected_users_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_expected_users_property" ],
            [ "CurrentRoomIsOfflineProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_offline_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_offline_property" ],
            [ "CurrentRoomIsOpenProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_open_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_open_property" ],
            [ "CurrentRoomIsVisibleProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_visible_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_is_visible_property" ],
            [ "CurrentRoomMasterClientIdProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_master_client_id_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_master_client_id_property" ],
            [ "CurrentRoomMaxPlayersProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_max_players_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_max_players_property" ],
            [ "CurrentRoomNameProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_name_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_name_property" ],
            [ "CurrentRoomPlayerCountProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_player_count_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_player_count_property" ],
            [ "CurrentRoomPlayerTtlProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_player_ttl_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_player_ttl_property" ],
            [ "CurrentRoomPropertiesListedInLobbyProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_properties_listed_in_lobby_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_current_room_properties_listed_in_lobby_property" ],
            [ "GameVersionProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_game_version_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_game_version_property" ],
            [ "IsConnectedAndReadyProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_is_connected_and_ready_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_is_connected_and_ready_property" ],
            [ "IsConnectedProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_is_connected_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_is_connected_property" ],
            [ "OfflineModeProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_offline_mode_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_offline_mode_property" ],
            [ "PingProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_ping_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_ping_property" ],
            [ "PropertyListenerBase", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_property_listener_base.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_property_listener_base" ],
            [ "ServerAddressProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_server_address_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_server_address_property" ],
            [ "ServerProperty", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_server_property.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_server_property" ],
            [ "ScoreHelper", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_score_helper.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_score_helper" ],
            [ "PunCockpitEmbed", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_pun_cockpit_embed.html", "class_photon_1_1_pun_1_1_demo_1_1_cockpit_1_1_pun_cockpit_embed" ]
          ] ],
          [ "Hub", "namespace_photon_1_1_pun_1_1_demo_1_1_hub.html", [
            [ "PunStartup", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_pun_startup.html", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_pun_startup" ],
            [ "DemoHubManager", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_demo_hub_manager.html", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_demo_hub_manager" ],
            [ "ToDemoHubButton", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_to_demo_hub_button.html", "class_photon_1_1_pun_1_1_demo_1_1_hub_1_1_to_demo_hub_button" ]
          ] ],
          [ "Procedural", "namespace_photon_1_1_pun_1_1_demo_1_1_procedural.html", [
            [ "Block", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_block.html", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_block" ],
            [ "Cluster", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_cluster.html", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_cluster" ],
            [ "IngameControlPanel", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_ingame_control_panel.html", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_ingame_control_panel" ],
            [ "ProceduralController", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_procedural_controller.html", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_procedural_controller" ],
            [ "WorldGenerator", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_world_generator.html", "class_photon_1_1_pun_1_1_demo_1_1_procedural_1_1_world_generator" ]
          ] ],
          [ "PunBasics", "namespace_photon_1_1_pun_1_1_demo_1_1_pun_basics.html", [
            [ "CameraWork", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_camera_work.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_camera_work" ],
            [ "GameManager", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_game_manager.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_game_manager" ],
            [ "Launcher", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_launcher.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_launcher" ],
            [ "LoaderAnime", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_loader_anime.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_loader_anime" ],
            [ "PlayerAnimatorManager", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_animator_manager.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_animator_manager" ],
            [ "PlayerManager", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_manager.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_manager" ],
            [ "PlayerNameInputField", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_name_input_field.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_name_input_field" ],
            [ "PlayerUI", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_u_i.html", "class_photon_1_1_pun_1_1_demo_1_1_pun_basics_1_1_player_u_i" ]
          ] ],
          [ "Shared", "namespace_photon_1_1_pun_1_1_demo_1_1_shared.html", [
            [ "DocLinks", "class_photon_1_1_pun_1_1_demo_1_1_shared_1_1_doc_links.html", "class_photon_1_1_pun_1_1_demo_1_1_shared_1_1_doc_links" ]
          ] ],
          [ "SlotRacer", "namespace_photon_1_1_pun_1_1_demo_1_1_slot_racer.html", [
            [ "Utils", "namespace_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils.html", [
              [ "Bezier", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier" ],
              [ "BezierCurve", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_curve.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_curve" ],
              [ "BezierSpline", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_spline.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_spline" ],
              [ "BezierCurveInspector", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_curve_inspector.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_curve_inspector" ],
              [ "BezierSplineInspector", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_spline_inspector.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_bezier_spline_inspector" ],
              [ "LineInspector", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_line_inspector.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_line_inspector" ],
              [ "Line", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_line.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_line" ],
              [ "SplinePosition", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_spline_position.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_spline_position" ],
              [ "SplineWalker", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_spline_walker.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_utils_1_1_spline_walker" ]
            ] ],
            [ "PlayerControl", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_player_control.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_player_control" ],
            [ "SlotLanes", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_slot_lanes.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_slot_lanes" ],
            [ "SlotRacerSplashScreen", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_slot_racer_splash_screen.html", "class_photon_1_1_pun_1_1_demo_1_1_slot_racer_1_1_slot_racer_splash_screen" ]
          ] ],
          [ "WebRpcImplementationExample", "class_photon_1_1_pun_1_1_demo_1_1_web_rpc_implementation_example.html", "class_photon_1_1_pun_1_1_demo_1_1_web_rpc_implementation_example" ]
        ] ],
        [ "UtilityScripts", "namespace_photon_1_1_pun_1_1_utility_scripts.html", [
          [ "CullArea", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cull_area.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cull_area" ],
          [ "CellTree", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cell_tree.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cell_tree" ],
          [ "CellTreeNode", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cell_tree_node.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cell_tree_node" ],
          [ "ByteComparer", "class_photon_1_1_pun_1_1_utility_scripts_1_1_byte_comparer.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_byte_comparer" ],
          [ "CullingHandler", "class_photon_1_1_pun_1_1_utility_scripts_1_1_culling_handler.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_culling_handler" ],
          [ "CullAreaEditor", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cull_area_editor.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_cull_area_editor" ],
          [ "PhotonLagSimulationGui", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_lag_simulation_gui.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_lag_simulation_gui" ],
          [ "PhotonStatsGui", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_stats_gui.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_stats_gui" ],
          [ "PointedAtGameObjectInfo", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pointed_at_game_object_info.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pointed_at_game_object_info" ],
          [ "StatesGui", "class_photon_1_1_pun_1_1_utility_scripts_1_1_states_gui.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_states_gui" ],
          [ "PhotonTeamsManagerEditor", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_teams_manager_editor.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_teams_manager_editor" ],
          [ "PlayerNumberingInspector", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering_inspector.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering_inspector" ],
          [ "PunTeamsInspector", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_teams_inspector.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_teams_inspector" ],
          [ "PhotonTeam", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_team.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_team" ],
          [ "PhotonTeamsManager", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_teams_manager.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_teams_manager" ],
          [ "PhotonTeamExtensions", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_team_extensions.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_photon_team_extensions" ],
          [ "PlayerNumbering", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering" ],
          [ "PlayerNumberingExtensions", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering_extensions.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_player_numbering_extensions" ],
          [ "PunPlayerScores", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_player_scores.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_player_scores" ],
          [ "ScoreExtensions", "class_photon_1_1_pun_1_1_utility_scripts_1_1_score_extensions.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_score_extensions" ],
          [ "PunTeams", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_teams.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_teams" ],
          [ "TeamExtensions", "class_photon_1_1_pun_1_1_utility_scripts_1_1_team_extensions.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_team_extensions" ],
          [ "SmoothSyncMovement", "class_photon_1_1_pun_1_1_utility_scripts_1_1_smooth_sync_movement.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_smooth_sync_movement" ],
          [ "ConnectAndJoinRandom", "class_photon_1_1_pun_1_1_utility_scripts_1_1_connect_and_join_random.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_connect_and_join_random" ],
          [ "MoveByKeys", "class_photon_1_1_pun_1_1_utility_scripts_1_1_move_by_keys.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_move_by_keys" ],
          [ "OnClickDestroy", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_destroy.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_destroy" ],
          [ "OnClickInstantiate", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_instantiate.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_instantiate" ],
          [ "OnClickRpc", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_rpc.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_click_rpc" ],
          [ "OnEscapeQuit", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_escape_quit.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_escape_quit" ],
          [ "OnJoinedInstantiate", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_joined_instantiate.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_joined_instantiate" ],
          [ "OnStartDelete", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_start_delete.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_start_delete" ],
          [ "CountdownTimer", "class_photon_1_1_pun_1_1_utility_scripts_1_1_countdown_timer.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_countdown_timer" ],
          [ "PunTurnManager", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_turn_manager.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_pun_turn_manager" ],
          [ "IPunTurnManagerCallbacks", "interface_photon_1_1_pun_1_1_utility_scripts_1_1_i_pun_turn_manager_callbacks.html", "interface_photon_1_1_pun_1_1_utility_scripts_1_1_i_pun_turn_manager_callbacks" ],
          [ "TurnExtensions", "class_photon_1_1_pun_1_1_utility_scripts_1_1_turn_extensions.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_turn_extensions" ],
          [ "ButtonInsideScrollList", "class_photon_1_1_pun_1_1_utility_scripts_1_1_button_inside_scroll_list.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_button_inside_scroll_list" ],
          [ "EventSystemSpawner", "class_photon_1_1_pun_1_1_utility_scripts_1_1_event_system_spawner.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_event_system_spawner" ],
          [ "GraphicToggleIsOnTransition", "class_photon_1_1_pun_1_1_utility_scripts_1_1_graphic_toggle_is_on_transition.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_graphic_toggle_is_on_transition" ],
          [ "OnPointerOverTooltip", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_pointer_over_tooltip.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_on_pointer_over_tooltip" ],
          [ "TabViewManager", "class_photon_1_1_pun_1_1_utility_scripts_1_1_tab_view_manager.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_tab_view_manager" ],
          [ "TextButtonTransition", "class_photon_1_1_pun_1_1_utility_scripts_1_1_text_button_transition.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_text_button_transition" ],
          [ "TextToggleIsOnTransition", "class_photon_1_1_pun_1_1_utility_scripts_1_1_text_toggle_is_on_transition.html", "class_photon_1_1_pun_1_1_utility_scripts_1_1_text_toggle_is_on_transition" ]
        ] ],
        [ "PunWizardText", "class_photon_1_1_pun_1_1_pun_wizard_text.html", "class_photon_1_1_pun_1_1_pun_wizard_text" ],
        [ "PhotonEditor", "class_photon_1_1_pun_1_1_photon_editor.html", "class_photon_1_1_pun_1_1_photon_editor" ],
        [ "PhotonGUI", "class_photon_1_1_pun_1_1_photon_g_u_i.html", "class_photon_1_1_pun_1_1_photon_g_u_i" ],
        [ "PhotonViewHandler", "class_photon_1_1_pun_1_1_photon_view_handler.html", "class_photon_1_1_pun_1_1_photon_view_handler" ],
        [ "PunSceneViews", "class_photon_1_1_pun_1_1_pun_scene_views.html", "class_photon_1_1_pun_1_1_pun_scene_views" ],
        [ "SceneSetting", "class_photon_1_1_pun_1_1_scene_setting.html", "class_photon_1_1_pun_1_1_scene_setting" ],
        [ "PunSceneSettings", "class_photon_1_1_pun_1_1_pun_scene_settings.html", "class_photon_1_1_pun_1_1_pun_scene_settings" ],
        [ "ServerSettingsInspector", "class_photon_1_1_pun_1_1_server_settings_inspector.html", "class_photon_1_1_pun_1_1_server_settings_inspector" ],
        [ "MonoBehaviourPunEditor", "class_photon_1_1_pun_1_1_mono_behaviour_pun_editor.html", "class_photon_1_1_pun_1_1_mono_behaviour_pun_editor" ],
        [ "PhotonAnimatorViewEditor", "class_photon_1_1_pun_1_1_photon_animator_view_editor.html", "class_photon_1_1_pun_1_1_photon_animator_view_editor" ],
        [ "PhotonRigidbody2DViewEditor", "class_photon_1_1_pun_1_1_photon_rigidbody2_d_view_editor.html", "class_photon_1_1_pun_1_1_photon_rigidbody2_d_view_editor" ],
        [ "PhotonRigidbodyViewEditor", "class_photon_1_1_pun_1_1_photon_rigidbody_view_editor.html", "class_photon_1_1_pun_1_1_photon_rigidbody_view_editor" ],
        [ "PhotonTransformViewClassicEditor", "class_photon_1_1_pun_1_1_photon_transform_view_classic_editor.html", "class_photon_1_1_pun_1_1_photon_transform_view_classic_editor" ],
        [ "PhotonTransformViewEditor", "class_photon_1_1_pun_1_1_photon_transform_view_editor.html", "class_photon_1_1_pun_1_1_photon_transform_view_editor" ],
        [ "IPhotonViewCallback", "interface_photon_1_1_pun_1_1_i_photon_view_callback.html", null ],
        [ "IOnPhotonViewPreNetDestroy", "interface_photon_1_1_pun_1_1_i_on_photon_view_pre_net_destroy.html", "interface_photon_1_1_pun_1_1_i_on_photon_view_pre_net_destroy" ],
        [ "IOnPhotonViewOwnerChange", "interface_photon_1_1_pun_1_1_i_on_photon_view_owner_change.html", "interface_photon_1_1_pun_1_1_i_on_photon_view_owner_change" ],
        [ "IOnPhotonViewControllerChange", "interface_photon_1_1_pun_1_1_i_on_photon_view_controller_change.html", "interface_photon_1_1_pun_1_1_i_on_photon_view_controller_change" ],
        [ "IPunObservable", "interface_photon_1_1_pun_1_1_i_pun_observable.html", "interface_photon_1_1_pun_1_1_i_pun_observable" ],
        [ "IPunOwnershipCallbacks", "interface_photon_1_1_pun_1_1_i_pun_ownership_callbacks.html", "interface_photon_1_1_pun_1_1_i_pun_ownership_callbacks" ],
        [ "IPunInstantiateMagicCallback", "interface_photon_1_1_pun_1_1_i_pun_instantiate_magic_callback.html", "interface_photon_1_1_pun_1_1_i_pun_instantiate_magic_callback" ],
        [ "IPunPrefabPool", "interface_photon_1_1_pun_1_1_i_pun_prefab_pool.html", "interface_photon_1_1_pun_1_1_i_pun_prefab_pool" ],
        [ "PhotonHandler", "class_photon_1_1_pun_1_1_photon_handler.html", "class_photon_1_1_pun_1_1_photon_handler" ],
        [ "InstantiateParameters", "struct_photon_1_1_pun_1_1_instantiate_parameters.html", "struct_photon_1_1_pun_1_1_instantiate_parameters" ],
        [ "PhotonNetwork", "class_photon_1_1_pun_1_1_photon_network.html", "class_photon_1_1_pun_1_1_photon_network" ],
        [ "PhotonStreamQueue", "class_photon_1_1_pun_1_1_photon_stream_queue.html", "class_photon_1_1_pun_1_1_photon_stream_queue" ],
        [ "PhotonView", "class_photon_1_1_pun_1_1_photon_view.html", "class_photon_1_1_pun_1_1_photon_view" ],
        [ "PunRPC", "class_photon_1_1_pun_1_1_pun_r_p_c.html", null ],
        [ "MonoBehaviourPun", "class_photon_1_1_pun_1_1_mono_behaviour_pun.html", "class_photon_1_1_pun_1_1_mono_behaviour_pun" ],
        [ "MonoBehaviourPunCallbacks", "class_photon_1_1_pun_1_1_mono_behaviour_pun_callbacks.html", "class_photon_1_1_pun_1_1_mono_behaviour_pun_callbacks" ],
        [ "PhotonMessageInfo", "struct_photon_1_1_pun_1_1_photon_message_info.html", "struct_photon_1_1_pun_1_1_photon_message_info" ],
        [ "PhotonStream", "class_photon_1_1_pun_1_1_photon_stream.html", "class_photon_1_1_pun_1_1_photon_stream" ],
        [ "SceneManagerHelper", "class_photon_1_1_pun_1_1_scene_manager_helper.html", "class_photon_1_1_pun_1_1_scene_manager_helper" ],
        [ "DefaultPool", "class_photon_1_1_pun_1_1_default_pool.html", "class_photon_1_1_pun_1_1_default_pool" ],
        [ "PunExtensions", "class_photon_1_1_pun_1_1_pun_extensions.html", "class_photon_1_1_pun_1_1_pun_extensions" ],
        [ "ServerSettings", "class_photon_1_1_pun_1_1_server_settings.html", "class_photon_1_1_pun_1_1_server_settings" ],
        [ "NestedComponentUtilities", "class_photon_1_1_pun_1_1_nested_component_utilities.html", "class_photon_1_1_pun_1_1_nested_component_utilities" ],
        [ "PhotonAnimatorView", "class_photon_1_1_pun_1_1_photon_animator_view.html", "class_photon_1_1_pun_1_1_photon_animator_view" ],
        [ "PhotonRigidbody2DView", "class_photon_1_1_pun_1_1_photon_rigidbody2_d_view.html", "class_photon_1_1_pun_1_1_photon_rigidbody2_d_view" ],
        [ "PhotonRigidbodyView", "class_photon_1_1_pun_1_1_photon_rigidbody_view.html", "class_photon_1_1_pun_1_1_photon_rigidbody_view" ],
        [ "PhotonTransformView", "class_photon_1_1_pun_1_1_photon_transform_view.html", "class_photon_1_1_pun_1_1_photon_transform_view" ],
        [ "PhotonTransformViewClassic", "class_photon_1_1_pun_1_1_photon_transform_view_classic.html", "class_photon_1_1_pun_1_1_photon_transform_view_classic" ],
        [ "PhotonTransformViewPositionModel", "class_photon_1_1_pun_1_1_photon_transform_view_position_model.html", "class_photon_1_1_pun_1_1_photon_transform_view_position_model" ],
        [ "PhotonTransformViewPositionControl", "class_photon_1_1_pun_1_1_photon_transform_view_position_control.html", "class_photon_1_1_pun_1_1_photon_transform_view_position_control" ],
        [ "PhotonTransformViewRotationModel", "class_photon_1_1_pun_1_1_photon_transform_view_rotation_model.html", "class_photon_1_1_pun_1_1_photon_transform_view_rotation_model" ],
        [ "PhotonTransformViewRotationControl", "class_photon_1_1_pun_1_1_photon_transform_view_rotation_control.html", "class_photon_1_1_pun_1_1_photon_transform_view_rotation_control" ],
        [ "PhotonTransformViewScaleModel", "class_photon_1_1_pun_1_1_photon_transform_view_scale_model.html", "class_photon_1_1_pun_1_1_photon_transform_view_scale_model" ],
        [ "PhotonTransformViewScaleControl", "class_photon_1_1_pun_1_1_photon_transform_view_scale_control.html", "class_photon_1_1_pun_1_1_photon_transform_view_scale_control" ]
      ] ],
      [ "Realtime", "namespace_photon_1_1_realtime.html", [
        [ "Demo", "namespace_photon_1_1_realtime_1_1_demo.html", [
          [ "ConnectAndJoinRandomLb", "class_photon_1_1_realtime_1_1_demo_1_1_connect_and_join_random_lb.html", "class_photon_1_1_realtime_1_1_demo_1_1_connect_and_join_random_lb" ]
        ] ],
        [ "AppSettings", "class_photon_1_1_realtime_1_1_app_settings.html", "class_photon_1_1_realtime_1_1_app_settings" ],
        [ "ConnectionHandler", "class_photon_1_1_realtime_1_1_connection_handler.html", "class_photon_1_1_realtime_1_1_connection_handler" ],
        [ "Extensions", "class_photon_1_1_realtime_1_1_extensions.html", "class_photon_1_1_realtime_1_1_extensions" ],
        [ "FriendInfo", "class_photon_1_1_realtime_1_1_friend_info.html", "class_photon_1_1_realtime_1_1_friend_info" ],
        [ "PhotonPortDefinition", "struct_photon_1_1_realtime_1_1_photon_port_definition.html", "struct_photon_1_1_realtime_1_1_photon_port_definition" ],
        [ "LoadBalancingClient", "class_photon_1_1_realtime_1_1_load_balancing_client.html", "class_photon_1_1_realtime_1_1_load_balancing_client" ],
        [ "IConnectionCallbacks", "interface_photon_1_1_realtime_1_1_i_connection_callbacks.html", "interface_photon_1_1_realtime_1_1_i_connection_callbacks" ],
        [ "ILobbyCallbacks", "interface_photon_1_1_realtime_1_1_i_lobby_callbacks.html", "interface_photon_1_1_realtime_1_1_i_lobby_callbacks" ],
        [ "IMatchmakingCallbacks", "interface_photon_1_1_realtime_1_1_i_matchmaking_callbacks.html", "interface_photon_1_1_realtime_1_1_i_matchmaking_callbacks" ],
        [ "IInRoomCallbacks", "interface_photon_1_1_realtime_1_1_i_in_room_callbacks.html", "interface_photon_1_1_realtime_1_1_i_in_room_callbacks" ],
        [ "IOnEventCallback", "interface_photon_1_1_realtime_1_1_i_on_event_callback.html", "interface_photon_1_1_realtime_1_1_i_on_event_callback" ],
        [ "IWebRpcCallback", "interface_photon_1_1_realtime_1_1_i_web_rpc_callback.html", "interface_photon_1_1_realtime_1_1_i_web_rpc_callback" ],
        [ "IErrorInfoCallback", "interface_photon_1_1_realtime_1_1_i_error_info_callback.html", "interface_photon_1_1_realtime_1_1_i_error_info_callback" ],
        [ "ConnectionCallbacksContainer", "class_photon_1_1_realtime_1_1_connection_callbacks_container.html", "class_photon_1_1_realtime_1_1_connection_callbacks_container" ],
        [ "MatchMakingCallbacksContainer", "class_photon_1_1_realtime_1_1_match_making_callbacks_container.html", "class_photon_1_1_realtime_1_1_match_making_callbacks_container" ],
        [ "ErrorInfo", "class_photon_1_1_realtime_1_1_error_info.html", "class_photon_1_1_realtime_1_1_error_info" ],
        [ "LoadBalancingPeer", "class_photon_1_1_realtime_1_1_load_balancing_peer.html", "class_photon_1_1_realtime_1_1_load_balancing_peer" ],
        [ "FindFriendsOptions", "class_photon_1_1_realtime_1_1_find_friends_options.html", "class_photon_1_1_realtime_1_1_find_friends_options" ],
        [ "OpJoinRandomRoomParams", "class_photon_1_1_realtime_1_1_op_join_random_room_params.html", "class_photon_1_1_realtime_1_1_op_join_random_room_params" ],
        [ "EnterRoomParams", "class_photon_1_1_realtime_1_1_enter_room_params.html", "class_photon_1_1_realtime_1_1_enter_room_params" ],
        [ "ErrorCode", "class_photon_1_1_realtime_1_1_error_code.html", "class_photon_1_1_realtime_1_1_error_code" ],
        [ "ActorProperties", "class_photon_1_1_realtime_1_1_actor_properties.html", "class_photon_1_1_realtime_1_1_actor_properties" ],
        [ "GamePropertyKey", "class_photon_1_1_realtime_1_1_game_property_key.html", "class_photon_1_1_realtime_1_1_game_property_key" ],
        [ "EventCode", "class_photon_1_1_realtime_1_1_event_code.html", "class_photon_1_1_realtime_1_1_event_code" ],
        [ "ParameterCode", "class_photon_1_1_realtime_1_1_parameter_code.html", "class_photon_1_1_realtime_1_1_parameter_code" ],
        [ "OperationCode", "class_photon_1_1_realtime_1_1_operation_code.html", "class_photon_1_1_realtime_1_1_operation_code" ],
        [ "RoomOptions", "class_photon_1_1_realtime_1_1_room_options.html", "class_photon_1_1_realtime_1_1_room_options" ],
        [ "RaiseEventOptions", "class_photon_1_1_realtime_1_1_raise_event_options.html", "class_photon_1_1_realtime_1_1_raise_event_options" ],
        [ "TypedLobby", "class_photon_1_1_realtime_1_1_typed_lobby.html", "class_photon_1_1_realtime_1_1_typed_lobby" ],
        [ "TypedLobbyInfo", "class_photon_1_1_realtime_1_1_typed_lobby_info.html", "class_photon_1_1_realtime_1_1_typed_lobby_info" ],
        [ "AuthenticationValues", "class_photon_1_1_realtime_1_1_authentication_values.html", "class_photon_1_1_realtime_1_1_authentication_values" ],
        [ "PhotonPing", "class_photon_1_1_realtime_1_1_photon_ping.html", "class_photon_1_1_realtime_1_1_photon_ping" ],
        [ "PingMono", "class_photon_1_1_realtime_1_1_ping_mono.html", "class_photon_1_1_realtime_1_1_ping_mono" ],
        [ "Player", "class_photon_1_1_realtime_1_1_player.html", "class_photon_1_1_realtime_1_1_player" ],
        [ "Region", "class_photon_1_1_realtime_1_1_region.html", "class_photon_1_1_realtime_1_1_region" ],
        [ "RegionHandler", "class_photon_1_1_realtime_1_1_region_handler.html", "class_photon_1_1_realtime_1_1_region_handler" ],
        [ "RegionPinger", "class_photon_1_1_realtime_1_1_region_pinger.html", "class_photon_1_1_realtime_1_1_region_pinger" ],
        [ "Room", "class_photon_1_1_realtime_1_1_room.html", "class_photon_1_1_realtime_1_1_room" ],
        [ "RoomInfo", "class_photon_1_1_realtime_1_1_room_info.html", "class_photon_1_1_realtime_1_1_room_info" ],
        [ "SupportLogger", "class_photon_1_1_realtime_1_1_support_logger.html", "class_photon_1_1_realtime_1_1_support_logger" ],
        [ "PhotonAppSettings", "class_photon_1_1_realtime_1_1_photon_app_settings.html", "class_photon_1_1_realtime_1_1_photon_app_settings" ],
        [ "WebRpcResponse", "class_photon_1_1_realtime_1_1_web_rpc_response.html", "class_photon_1_1_realtime_1_1_web_rpc_response" ],
        [ "WebFlags", "class_photon_1_1_realtime_1_1_web_flags.html", "class_photon_1_1_realtime_1_1_web_flags" ]
      ] ]
    ] ],
    [ "Simplex", "namespace_simplex.html", [
      [ "Noise", "class_simplex_1_1_noise.html", "class_simplex_1_1_noise" ]
    ] ],
    [ "UnityStandardAssets", "namespace_unity_standard_assets.html", [
      [ "Characters", "namespace_unity_standard_assets_1_1_characters.html", [
        [ "ThirdPerson", "namespace_unity_standard_assets_1_1_characters_1_1_third_person.html", [
          [ "PunDemos", "namespace_unity_standard_assets_1_1_characters_1_1_third_person_1_1_pun_demos.html", [
            [ "ThirdPersonCharacter", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_pun_demos_1_1_third_person_character.html", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_pun_demos_1_1_third_person_character" ],
            [ "ThirdPersonUserControl", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_pun_demos_1_1_third_person_user_control.html", "class_unity_standard_assets_1_1_characters_1_1_third_person_1_1_pun_demos_1_1_third_person_user_control" ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "AI", "class_a_i.html", "class_a_i" ],
    [ "BoardController", "class_board_controller.html", "class_board_controller" ],
    [ "CameraController", "class_camera_controller.html", "class_camera_controller" ],
    [ "CardDragger", "class_card_dragger.html", "class_card_dragger" ],
    [ "ChatEditor", "class_chat_editor.html", "class_chat_editor" ],
    [ "ConnectToServer", "class_connect_to_server.html", "class_connect_to_server" ],
    [ "CreateAndJoinRoom", "class_create_and_join_room.html", "class_create_and_join_room" ],
    [ "GameController", "class_game_controller.html", "class_game_controller" ],
    [ "HandController", "class_hand_controller.html", "class_hand_controller" ],
    [ "HttpSender", "class_http_sender.html", "class_http_sender" ],
    [ "SpawnPlayers", "class_spawn_players.html", "class_spawn_players" ]
];